### ISSUE TITLE
Gogoloot picks up Items wenn in Raidgroup but no instance!

### ISSUE THREAD

**Issue by DieQuelle** [Gogo1951/GogoLoot#105]
Hey Guys,

just a head a really bad - experience with your addon.

We did a Worldboss, i had my gogoloot on (i was LM).
And suddendly I was 2 items richer, eventho they are bound on pickup.

So please, add a failback if somebody is not in an instance or any other failback....
(or add items to global ignore list for all worlds bosses and bound on pickup items)

I mean, should be an easy thing to do but maybe im just a litle nerve wracked by the amount of flame I just got.

Lets hope Indie Company Blizzard will relocate the items correctly....

Best Regards, dq

**Comment by Gogo1951** [comment]
You're on a really old version I think. GogoLoot was updated at the start of TBC to ignore world boss drops.

**Comment by Gogo1951** [comment]
@DieQuelle Let me know what version you are on. This was fixed back in August I think.

**Comment by Gogo1951** [comment]
Thanks, I'll dig into this. Loot is BOE now, but still shouldn't have looted if you weren't in an instance.
