### ISSUE TITLE
WOTLK error

### ISSUE THREAD

**Issue by SegoItCh** [Gogo1951/GogoLoot#107]
1x GogoLoot\loot-Loot.lua:907: attempt to index global 'UnitPopupButtons' (a nil value)
[string "@GogoLoot\loot-Loot.lua"]:907: in function <GogoLoot\loot.lua:783>

Locals:
capitalize = <function> defined @GogoLoot\loot.lua:784
printInvalid = <function> defined @GogoLoot\loot.lua:787
events = <unnamed> {
 0 = <userdata>
}
canLoot = true
lootAPIOpen = false
lootTicker = nil
lastItemHidden = false
(*temporary) = nil
(*temporary) = <table> {
 color = <table> {
 }
 text = "Epic"
 checkable = 1
}
(*temporary) = <table> {
 hex = "|cffa334ee"
 r = 0.639216
 color = <table> {
 }
 g = 0.207843
 b = 0.933333
}
(*temporary) = "ITEM_QUALITY1_DESC"
(*temporary) = "ITEM_QUALITY2_DESC_GL"
(*temporary) = "ITEM_QUALITY3_DESC_GL"
(*temporary) = "ITEM_QUALITY4_DESC_GL"
(*temporary) = "CANCEL"
(*temporary) = "attempt to index global 'UnitPopupButtons' (a nil value)"
debug = <function> defined @GogoLoot\loot.lua:1

**Comment by cltnschlosser** [comment]
Fixed by #108

**Comment by Gogo1951** [comment]
Hey @cltnschlosser , I merged in the code, but BigWigs Pacakger needs to be updated as well so this can be released.

If you're interested in taking this over, happy to link you in. Ping me on Discord. Gogo1951.
