### ISSUE TITLE
Notification Announcements in Party / Raid

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#11]
Removed parts of this task that were completed already.

# On Out of Range

/raid (or party):{rt4} GogoLoot : Tried to loot {item(s)} to {player}, but {player} was out of range or not in the instance.

# Not Eligible

/raid (or party):{rt4} GogoLoot : Tried to loot {item} to {player}, but {player} was not eligible.

# Bags Full

/raid (or party):{rt4} GogoLoot : Tried to loot {item} to {player}, but {player}'s bags are full.

**Comment by Gogo1951** [comment]
Good idea to have it:

{rt4} GogoLoot : {Color 1}, {Color 2} items will go to {Player1}!
{rt4} GogoLoot : {Color 3}, {Color 4}, {Color 5} items will go to {Player2}!

**Comment by Gogo1951** [comment]
Ok for errors and edge cases to come later. Moving to Planning.

**Comment by Er00** [comment]
It would also be useful to be able to disable output entirely, and alter which channel output goes to.

**Comment by Gogo1951** [comment]
Covered in other tickets.
