### ISSUE TITLE
LUA error after patch 1.14.4 on Classic ERA WoW

### ISSUE THREAD

**Issue by mimixy** [Gogo1951/GogoLoot#110]
Hi there. I heavily rely on your addon in raids, as you can imagine. A couple days ago Classic ERA WoW received a big patch to get ready for Hard Core that lands this week. The patch broke most addons. Your addon is also affected. Hopefuly this is a straight foward fix for you. It is easy to replicate. The error appears everytime you log on to the game. You don't have to be in raid or anything.

Here is the LUA error from bugsack/bug grabber.

33x GogoLoot/loot.lua:907: attempt to index global 'UnitPopupButtons' (a nil value)
[string "@GogoLoot/loot.lua"]:907: in function <GogoLoot/loot.lua:783>

Locals:
capitalize = <function> defined @GogoLoot/loot.lua:784
printInvalid = <function> defined @GogoLoot/loot.lua:787
events = Frame {
 0 = <userdata>
}
canLoot = true
lootAPIOpen = false
lootTicker = nil
lastItemHidden = false
(*temporary) = nil
(*temporary) = <table> {
 color = <table> {
 }
 text = "Epic"
 checkable = 1
}
(*temporary) = <table> {
 hex = "|cffa335ee"
 r = 0.639216
 color = <table> {
 }
 g = 0.207843
 b = 0.933333
}
(*temporary) = "ITEM_QUALITY1_DESC"
(*temporary) = "ITEM_QUALITY2_DESC_GL"
(*temporary) = "ITEM_QUALITY3_DESC_GL"
(*temporary) = "ITEM_QUALITY4_DESC_GL"
(*temporary) = "CANCEL"
(*temporary) = "attempt to index global 'UnitPopupButtons' (a nil value)"
debug = <function> defined @GogoLoot/loot.lua:1

**Comment by KaylinFinke** [comment]
Please grab v1.11 and let me know if this resolves your issue.

**Comment by mimixy** [comment]
> 

downloaded, no lua error upon log on anymore.

**Comment by KaylinFinke** [comment]
Thanks.
