### ISSUE TITLE
Update "Ignore Item" instructional text

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#13]
> Items in this list will always show up for manual need or greed rolls.

> Enter Item ID, or Drag Item on to Input.

> [Field] [Ignore Item Button]

![image](https://user-images.githubusercontent.com/55365231/99915106-3e48bb00-2cc7-11eb-9757-ef49c3045d55.png)

Need similar text on the ML ignore list as well.

**Comment by Gogo1951** [comment]
![New Mockup 1](https://user-images.githubusercontent.com/55365231/99919414-eddf5680-2ce2-11eb-8b0d-142cb052b02e.png)

**Comment by Gogo1951** [comment]
Not quite the same issue... but can we make sure the default Need / Greed ignores are:

https://classic.wowhead.com/item=12811/righteous-orb

https://classic.wowhead.com/item=4500/travelers-backpack

And the default ML Ignore items are:

https://classic.wowhead.com/item=21321/red-qiraji-resonating-crystal

https://classic.wowhead.com/item=21323/green-qiraji-resonating-crystal

https://classic.wowhead.com/item=21324/yellow-qiraji-resonating-crystal

https://classic.wowhead.com/item=21218/blue-qiraji-resonating-crystal

https://classic.wowhead.com/item=17966/onyxia-hide-backpack

https://classic.wowhead.com/item=19914/panther-hide-sack

https://classic.wowhead.com/search?q=Swift+Razzashi+Raptor

https://classic.wowhead.com/item=19902/swift-zulian-tiger

**Comment by Gogo1951** [comment]
![New Mockup 1](https://user-images.githubusercontent.com/55365231/99919772-1a946d80-2ce5-11eb-8282-7d4b751dc9de.png)

**Comment by AeroScripts** [comment]
Should be good with next commit
