### ISSUE TITLE
Support for Softres.it CSV

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#14]
Need to add another section inside of the Master Looter Settings tab for support for SoftRes.it CSV import.

Contents of section hidden / disabled unless user was Master Looter.

Contents of tab should clear whenever a user joins a Party / Raid.

Under Loot Destinations, above Ignored Items:

> GogoLoot supports Softres.it; paste CSV code from website here to enable automatic distribution for this raid.

> [Input box]

# Format of Softres.it CSV

You can make a list here.

https://softres.it/

```
ItemId,Name,Class,Note,Plus
21503,Testname,Hunter,,2
21499,Testname,Hunter,,2

```

# Output

## On Save:

{standard loot destinations output}

{rt4} GogoLoot : Softres.it List Imported! {#} Reserves across {#} Items included.

## On Loot:

When an item is looted:

{rt4} GogoLoot : Per Softres.it List, {item} goes to {Player1}!

or

{rt4} GogoLoot : Per Softres.it List, {item} will be rolled on by {Player1}, {Player2}, ...!

**Comment by Gogo1951** [comment]
![New Mockup 1](https://user-images.githubusercontent.com/55365231/99919973-406e4200-2ce6-11eb-9a4b-228c5460fa4a.png)

**Comment by Gogo1951** [comment]
![New Mockup 1](https://user-images.githubusercontent.com/55365231/99920012-8b885500-2ce6-11eb-9f4c-34f3fc81f7c8.png)

**Comment by Gogo1951** [comment]
Few edge case thoughts.

When SR and Ignore conflict, SR wins and loot is handled by SR.

Once an item is looted via SR, it should be removed from the SR list. Possible for more than 1 item to drop, and not all are unique. Possible to get like 2 Cauterizing Bands... but only 1 should go via SR... 

And again, if more than 1 person SR's an item, even if 2 drop off the same boss (super rare) we'd just toss the items in the ML's bag and announce a roll anyway.

**Comment by AeroScripts** [comment]
What do you think about giving softres it's own tab? thats a lot to fit in vertically

**Comment by Gogo1951** [comment]
Let's give SR it's own tab. Good call. 

Also if it was meant to go to a player but we can't find that player...

{rt4} GogoLoot : Per Softres.it List, {item} goes to {Player1}... but we can't find {Player1}. The Master Looter will sort this out.

**Comment by AeroScripts** [comment]
This is mostly implemented now, it just needs some testing

**Comment by Gogo1951** [comment]
Need Checkbox for turning on SoftRes.it.
