### ISSUE TITLE
Hide Master Looter settings when Not Master Looter

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#15]
Should still be able to adjust ignore list.

**Comment by Gogo1951** [comment]
![New Mockup 1](https://user-images.githubusercontent.com/55365231/99919667-698dd300-2ce4-11eb-89f2-d0ac5f11fe1a.png)

**Comment by AeroScripts** [comment]
Should be solved but we can discuss this more if the current solution isn't ideal
