### ISSUE TITLE
Changing Loot Threshold in Combat

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#21]
<img width="652" alt="Screen Shot 2020-11-27 at 9 08 09 AM" src="https://user-images.githubusercontent.com/55365231/100462603-1cb54e00-3090-11eb-8215-fac26bc6adcf.png">

We need a way to tell the user that they can't change the loot threshold during combat. A user sets it in the UI, but they don't really set it because someone in the raid is in combat and then apparently things get mismatched between loot threshold and destinations.

Maybe we check to see if anyone is in combat, and if so we just close the window? Whatever is easier here. Simple output in chat would work too.

**Comment by AeroScripts** [comment]
When the dropdown is changed, it attempts to change the loot threshold immediately

We could have it check if the loot threshold is actually changed at that point.  If not make a popup that says "Loot threshold cant be changed in combat" or something. only 2-3 more lines of code to do that

**Comment by AeroScripts** [comment]
Should be good with the next commit
