### ISSUE TITLE
Add "Standard Master Loot Window" to Master Looter Destinations

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#27]
Some people want to use GogoLoot for just grays, whites, greens, & blues... and keep the standard Master Looter window for Purples.

To enable this, we need an option in each destination for "Standard Master Loot Window" -- and any loot set to this would show up in a standard loot window for the Master Looter to deal with.

This came from a guy on the SoftRes.It Discord. It was in one of my early sketches for Loot Destinations, but it didn't make the priority cut for V1. (=

**Comment by AeroScripts** [comment]
Implemented as of v1.3
