### ISSUE TITLE
GGL Overrides WoW's Autoloot Setting

### ISSUE THREAD

**Issue by Er00** [Gogo1951/GogoLoot#30]
When I installed this addon it overrode WoW's settings for autoloot - I had autoloot off (with shift as the modifier key), however after installing this addon autoloot was then enabled in WoW's interface options.

**Comment by Gogo1951** [comment]
Hey @Er00 ,

This is by design. It's so "speedy auto loot" will work -- if you don't have auto loot on, speedy auto loot won't fire.

**Comment by Er00** [comment]
Then with speedy loot off surely it shouldn't override the WoW setting (but it certainly seems to)?

**Comment by Gogo1951** [comment]
Hey mate, lots of things going on. Appreciate the feedback here but this is super low on my priority list.

I'd think just about anyone using an addon like this would have auto-loot enabled.
