### ISSUE TITLE
GGL Settings (Sometimes?) Don't Save

### ISSUE THREAD

**Issue by Er00** [Gogo1951/GogoLoot#31]
Apologies in advance, this is quite a rubbish bug report - I'll try to investigate further tomorrow if I can.

It seems that (sometimes?) GGL doesn't save its settings in terms of which boxes are ticked in the first tab (eg speedy loot). I've not noticed a specific pattern for when it seems to reset, I thought it was resetting every time but just relogged and it *was* saved that time so, yeah, sorry for lack of repro and I'll work on that!

**Comment by Gogo1951** [comment]
Hey @Er00 ,

There are a few kinks we're still working out, if you can find any more on this happy to dive into it further. I haven't seen this behavior, but certainly open to the idea that there are bugs we haven't found. (=

I'll keep this open while you investigate. Thanks!

**Comment by Gogo1951** [comment]
Hey @Er00 ,

New version of GogoLoot is out; mind investigating to see if you can reproduce this issue?

**Comment by Er00** [comment]
I've struggled to repro it (it definitely seemed to happen a few times before I filed this report but nothing since) so I'll put it down to either user error or something that's fixed in latest version! Can always reopen if it comes back.

**Comment by Gogo1951** [comment]
@Er00 ,

Thanks!

There are a few bugs we're tracking / working on. If you see any others add 'em to the list. Appreciate the feedback!

https://github.com/Gogo1951/GogoLoot/projects/1
