### ISSUE TITLE
World Boss epic loot should be default ignored

### ISSUE THREAD

**Issue by kdim953** [Gogo1951/GogoLoot#40]
World boss loot is not tradable. All epic item world boss loot should be added to the default ignore list.

**Comment by Gogo1951** [comment]
That's a very good point! Will add this.

**Comment by Gogo1951** [comment]
@kdim953 

If you have time please spot check this list of item IDs. I think it's complete.

20577
20578
20579
20580
20581
20582
20599
20615
20616
20617
20618
20619
20621
20622
20623
20624
20625
20626
20627
20628
20630
20631
20632
20633
20634
20635
20636
20637
20638
20639
20644
22389
22390
22890

**Comment by kdim953** [comment]
Missing a few, heres full list:

17070
17111
17112
17113
18202
18204
18208
18541
18542
18543
18544
18545
18546
18547
19130
19131
19132
19133
19134
19135
20577
20578
20579
20580
20581
20582
20599
20615
20616
20617
20618
20619
20621
20622
20623
20624
20625
20626
20627
20628
20629
20630
20631
20632
20633
20634
20635
20636
20637
20638
20639
20644

**Comment by kdim953** [comment]
You have a few plans / non locked BOE on your list you can remove.

**Comment by Gogo1951** [comment]
@AeroScripts Please spot check this. Thanks!

https://github.com/Gogo1951/GogoLoot/commit/1a51cef4059246ca8cdc9778b3796f848d769a76

**Comment by AeroScripts** [comment]
I'm adding some code to prevent master-looting an item if the following conditions are met:
- the item is bind on pickup
- you (the master looter) are not currently zoned into a raid instance that makes BOP loot tradable

Should solve the issue in all cases

**Comment by Gogo1951** [comment]
Need to update lists back to not have all the items since we are addressing this another way.
