### ISSUE TITLE
Warning at Launch if Player has BetterAutoLoot or SpeedyAutoLoot Installed

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#41]
"GogoLoot : You have multiple addons running that are attempting to interact with the loot window. This will cause problems. If you don't disable your other loot addons you will experience issues with GogoLoot."

These can conflict. 

https://www.curseforge.com/wow/addons/auto-destroy
https://www.curseforge.com/wow/addons/auto-loot-assist
https://www.curseforge.com/wow/addons/autolooter
https://www.curseforge.com/wow/addons/better-autoloot
https://www.curseforge.com/wow/addons/cepgp
https://www.curseforge.com/wow/addons/communitydkp
https://www.curseforge.com/wow/addons/lootfast2
https://www.curseforge.com/wow/addons/rclootcouncil-classic
https://www.curseforge.com/wow/addons/speedyautoloot

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/105126929-5e1d1500-5aa5-11eb-976f-a3aa270d8701.png)

**Comment by Gogo1951** [comment]
Please move this paragraph to the top.

![image](https://user-images.githubusercontent.com/55365231/105127024-9290d100-5aa5-11eb-9005-4293fa1339dd.png)

**Comment by rainecheck** [comment]
Does this also conflict with the faster loot feature in Leatrix Plus?

**Comment by Gogo1951** [comment]
Probably.

**Comment by AeroScripts** [comment]
Any preference on font color?

**Comment by Gogo1951** [comment]
@AeroScripts 

Red.

"{rt4} GogoLoot : You have multiple addons running that are attempting to interact with the loot window. This will cause problems. If you don't disable your other loot addons you will experience issues with GogoLoot."
