### ISSUE TITLE
Softres.it Automatic Looting Not Working

### ISSUE THREAD

**Issue by Er00** [Gogo1951/GogoLoot#44]
Just killed Patchwerk, https://softres.it/raid/upw54r, two items that dropped were Wand of Fates (1 person SRed) and Desecrated Spaulders (4 people SRed). 

GoGoLoot with the settings imported (and chat output on closing the GGL window confirmed 76 reserves across 27 items) and checkbox ticked did nothing.

Version 1.5
I was Master Looter but not Raid Leader

Gogoloot data from softres.it:
```eNql2M1OGzEQB/BXifacw2aThcCNqBRUQtWKCKRWHIbdIWvFayN/hI1Q36Zv0herc2l7+Xtrc4yTn8a7nhnbeStEW5wX/uW1XphiWghlHamGw5iiYTDUkw3DVj87w5bNnm1x/v2tEI774ryqzk7KaWG0lCutfPgqfFLUH/ml8aQUBay0Ow4UP6Z/3fykznHzspohJ8NvFAx3msPOlkvA7lm9kISzPK1zXCTeR0Nb23nl2AC7rMpcG+aL7Gcyw6DYJr/XUYiedMW6aZA6rdLVvFwsgNp4I1iiYHUWW5YoQ9fasGSR/Eaibl6WaO1uDD3ZJ2+2OGdmdb4t0XzvOu3IaDDfClZw1IXlmAP3gUQvMFvmMbT4l7ahPbXwveB5jksU80ERriQYL6pwtvmGXFZ6xyGOeMM7K3bJJR9ncF+6Zim17ajvD8ld+D32qydDygnFbfKe+B77jVixGKCb5bjIjrHWWh0Ozkd6P1zSURvpdvdkWhgSN6tMdk2vOnmKGIVOjCJ9CSWlTZvcM0YcLqtfP43kXXoVjzhcj43TZuiTEzQbXliv6FWobXItjUt0HNqwMewN7BrzLBc5fvFepPf+uIJH6D3Lg+LkaCMO7mtr34sIW2SwcK9A+bnR1llS2/Qz+5jENXHFhmTLketMnSkjjZAHpf22c+mdNy4jmXOnvZSZN5P/sPDcfyF39CxF44833dTHHcchCU8AvhVSw1Wt6xwFs+hGSnhMgc0xgnBHXZOxUshOS5cccNxGOojpDxZGLDMUbh9Xhqx9YoJb6tlylkQfp0UXhv75W+Xxz7cr2kyGya22dlItXDf5RMflb4Vtjlv6Uf8GxmVoIQ==```

**Comment by Gogo1951** [comment]
Hey @Er00 ,

Will be fixed in the next release! Gotta run a few more tests before we push the code.

Thanks for calling out the issue.

**Comment by Gogo1951** [comment]
Fixed in latest release.

**Comment by Er00** [comment]
I'm afraid it still seems to be broken for me, had it in both BWL and MC tonight where there was only one SR on an item, the box was checked, the GL string was imported, and nothing happened.

One example:
![image](https://user-images.githubusercontent.com/6715812/107831031-0d879780-6d85-11eb-98dc-3ea425550a90.png)
![image](https://user-images.githubusercontent.com/6715812/107831049-1710ff80-6d85-11eb-85a2-e097e28161a3.png)
https://softres.it/raid/fy244o

**Comment by Gogo1951** [comment]
Hey @Er00 ,

We're 100% on Questie until BC, not likely going to have time for this. Sorry mate. 

Reopening issue and we'll look at it soon as there's time.

Thanks, and sorry for the hassle.

FYI: https://old.reddit.com/r/classicwow/comments/liyxyb/upcoming_questie_updates/

**Comment by Er00** [comment]
No worries at all, if/when you get to looking at this let me know if there's any further info I can provide!

**Comment by Gogo1951** [comment]
We ran this tonight, didn't see any issues. @Er00 feel free to re-open if you think this is still a problem.

**Comment by Er00** [comment]
In 1.6 or have you got a newer version in dev you used? The issues I saw above were in 1.6 so although I can try again I don't expect it to work any differently!

**Comment by Gogo1951** [comment]
Doesn't sound like you use this feature regularly?

We tested for 2-3 hours last night. Huge amount of time, didn't see any bugs. It handed out all items, other than the "quest" items like the Heart of Hakkar fine. We'll add a fix for quest items, but it seems to work and you're the only person who has raised concerns about it not working... hard to dedicate any more time to it given it seems to work and doesn't seem like many people use the feature.

**Comment by Er00** [comment]
Yeah, that's fair. I have tried to use it extensively but never had it work, I don't have any other loot addons which might be interfering but I'm not sure what might make a difference. If it starts working at some point in the future that'll be cool, til then I'll stick to the WA (and trying it in GL every ver update just in case ;) ). :)
