### ISSUE TITLE
Extra loot window popping up on looting

### ISSUE THREAD

**Issue by f90** [Gogo1951/GogoLoot#45]
Hey, loving your addon! Thanks! I have one slight issue with it however. When I loot sth that does not get auto-picked up (left to master looter) I get a loot window that does NOT close when I simply leave the loot behind. I cant move this window and I am not sure what it is even for. Can this be disabled so it doesn't show up at all?

See the example below - I am looting a mob and get the normal loot window by ElvUI, but also this extra window in the top left that has no functionality.

![grafik](https://user-images.githubusercontent.com/23065103/106050346-6699cf00-60e7-11eb-81dd-ed634f0bab6b.png)

**Comment by Gogo1951** [comment]
Hey @f90 , what other addons do you have running for loot? 

I suspect there's a conflict. Let me know so I can try and test them.

**Comment by f90** [comment]
Hey, here is my list of active addons:

AtlasLootClassic
ClassicGuildBank
CT_Library + CT_MailMod
Details!
Elkanos BUffbars
Exorsus Raid Tools
Extended Character Stats
Guild Export
Guild Roster Manager
IceHUD
Item Rack
Leatrix Maps
Leatrix Plus
Nova World Buffs
oRA 3
Quartz
Raid Invite Classic
RollTracker Classic
WeakAuras
Wide Quest Log
WIM
TSM
ElvUI Classic
Community DKP
DBM
GogoLoot v1.5
Questie

Maybe I can try reproducing the error without any other addons loaded, although it's going to be a bit annoying since I am masterlooting in the raid. I will report back if I find anything

**Comment by Gogo1951** [comment]
Hey @f90 ,

Can you try and disable "Community DKP" and see if you still have the problem? It's quite a bit ask for me to install a bunch of addons just to diagnose, y'know? I did go through the list and that one stood out as being likely as the culprit. Verify it and I'll try and dig into the code later. 

In all likelihood they won't work together. Like, both are trying to do something to the Loot Window, one is trying to scan the list and record it all, the other is trying to make the window go away as fast as possible... I'd have to reach out to the other dev and get them to refactor their code and likely refactor my code... and oof. It's a lot of work.

Addons aren't like real software; we don't like make any money off this. And that level of debugging is pretty damn tedious for a passion project. (=

Anyway verify if it's the culprit for me at least? Can sort next steps when we know.

**Comment by Gogo1951** [comment]
Hey @f90 ,

Was it Community DKP causing the conflict?

**Comment by Gogo1951** [comment]
Closing due to lack of response.

**Comment by f90** [comment]
@Gogo1951 Hey, can not test it at the moment since I am the loot master in our raids and have to keep DKP running as well, so cannot easily deactivate CommunityDKP to check. I suggest keeping this issue open though since it's not resolved, and somebody might see this and find the time/opportunity to test it at some point.

**Comment by Gogo1951** [comment]
Going to add a "conflict found" warning. https://github.com/Gogo1951/GogoLoot/issues/41

Should help.
