### ISSUE TITLE
Master Looter Active! message posts when no settings changed

### ISSUE THREAD

**Issue by rainecheck** [Gogo1951/GogoLoot#48]
the "GogoLoot : Master Looter Active! Blue, Gray, Green, Purple, and White items will go to <person>" message posts every time you close the `/gogoloot` window, even if you haven't changed anything about the master looting. I agree that it should post that it's on, but please consider only stating that master looting is active if there's a material change to the looting conditions.

**Comment by Gogo1951** [comment]
Hey @rainecheck ,

Sorry I thought I responded to this already.

Good catch! We'll get this fixed in an upcoming patch.

We're really 100% focused on Questie right now, don't expect any more changes to GogoLoot until Questie is functionally complete in BC.

Wish there were more hours in the day! (=
