### ISSUE TITLE
Revert in-game autoloot setting when not MLing

### ISSUE THREAD

**Issue by bindi** [Gogo1951/GogoLoot#49]
It seems that this addon relies on using the stock in-game autoloot functionality, which is fine. But after finishing a raid I logged on to an alt, and I wanted to check inside a chest without looting it, and it emptied it in my inventory. I noticed that on WoW settings my autoloot was enabled.

Can the autoloot setting be enabled only when masterlooting, and otherwise reverted back off if that was the original setting?

**Comment by Gogo1951** [comment]
We need "auto loot" to be on in order for GogoLoot to work. Not keen on re-working the add-on to account for people who don't want to use it. Just uninstall it.

**Comment by bindi** [comment]
I'm sorry, did you wake up on the wrong side of the bed before reading my post?

I said using auto-loot is **fine**. What I don't want to do however, is autoloot **everything** while I am **not masterlooting** - in my example I logged an alt and looked inside a quest item chest, and it emptied it all into my inventory. Not what I was expecting.

Can gogoloot only enable autoloot in-game when the addon is actually being used?

**Comment by Gogo1951** [comment]
Will look into it for BC. #51

**Comment by Gogo1951** [comment]
And @bindi ,

It's fun to build addons... but once they work enough for me... it's not really fun to hammer out edge cases or needs of other people. Y'know? Like you're asking for something you want, and like I respect you want to play the way you do... you're asking me to do work for something that I don't get any benefit from. That's all. 

I want this to be successful, and I want people to be happy using it, but I also want time to play the game and raid, and most importantly work on Questie. Gotta get that ready for BC. 

Anyway not trying to be a dick, just the nature of open source projects. If you want to submit a PR happy to review it... just hard to get motivation to do work on things I don't personally need. That's all.

Cheers!
