### ISSUE TITLE
After passing ML, gogoloot no longer works for a mob I am the ML on

### ISSUE THREAD

**Issue by bindi** [Gogo1951/GogoLoot#50]
After passing ML to someone else (for gbid addon purposes) but while still the person eligible to masterloot a boss, gogoloot does not work and will only offer to grant items manually, unsuccessfully. I tried to ML myself an item and it caused massive lagspike and it went to some other person instead of me.

Steps to reproduce:
- Be ML
- Kill boss
- Change ML to someone else before clearing out boss
- Unable to auto nor manual loot boss anymore

**Comment by Gogo1951** [comment]
There's no way to fix this. We don't have access to "this is your loot" in the loot API. Maybe in BC.

Just make sure you loot everything before switching Master Looter. I can't think of a development solution that would accomplish this, better to just default to that best practice.
