### ISSUE TITLE
Gogoloot announces autoneed on BoEs even when it's disabled

### ISSUE THREAD

**Issue by bindi** [Gogo1951/GogoLoot#53]
I was in a ZG run where the loot is changed from master loot to group loot back and forth, and every time group loot is enabled, GogoLoot announces that I am autoneeding on BoEs even though I specifically have that setting disabled.
![boe-need](https://user-images.githubusercontent.com/1408568/110225422-27347e80-7eee-11eb-9c9a-55e2ea7d070a.png)

**Comment by Gogo1951** [comment]
You aren't on latest. Make sure you update your addons daily.

https://www.getajour.com/

**Comment by bindi** [comment]
I'm using CurseBreaker and specifically made sure that i'm up to date - but that's from CurseForge though. It supports Github as well, but they are the same version as far as the numbering tells me?

**Comment by Gogo1951** [comment]
You aren't on the latest. 1.6 is the latest.

https://www.curseforge.com/wow/addons/gogoloot

https://github.com/Gogo1951/GogoLoot/releases/tag/v1.6 - 28 days old.

**Comment by bindi** [comment]
Up-to-date     │ GogoLoot by aerorocks99, gogo913    │ GogoLoot-v1.6.zip

**Comment by Gogo1951** [comment]
Mate, you aren't on the latest. Don't know what else to tell you. Use Ajour or WoWUp and tell me what it comes back with. You're a month out of date.

**Comment by Gogo1951** [comment]
In my opinion, anyone not using Ajour is doing it wrong.

Ajour has backups and a bunch of great features to keep your addons safe.

They do it right. No clue about the tool you used, but I wouldn't trust it given it tells you that you're on 1.6 but aren't actually.

**Comment by Gogo1951** [comment]
> C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\GogoLoot\GogoLoot.toc

Does it say "## Title: |cFFFFFFFFGogoLoot|r|cFF00FF00 v1.6|r"?

**Comment by bindi** [comment]
Yes. I just ran force update command to update the addon and I verified what you asked in the previous post, it's still announcing I'm autoneeding on BoEs (option still disabled).

**Comment by Gogo1951** [comment]
I haven't got a clue how that tool works, but I suspect poorly. Can you use Ajour?

**Comment by Gogo1951** [comment]
Send me a screenshot of your addons folder? Do you have duplicate versions installed?
