### ISSUE TITLE
bone fragment blacklisted from auto ML

### ISSUE THREAD

**Issue by unfortunatehippo** [Gogo1951/GogoLoot#58]
i am farming strat using the autoloot settings, all white items get autolooted apart from bone frags, they arent on  my blacklist

**Comment by unfortunatehippo** [comment]
i should clarify this is a bug with auto masterloot

**Comment by Gogo1951** [comment]
Hey mate, will check it out.

**Comment by Gogo1951** [comment]
@unfortunatehippo Blizzard API calls Bone Fragments a Quest Item... we ignore quest items. This is a bug with the Blizzard API.
