### ISSUE TITLE
Classic Era Bug

### ISSUE THREAD

**Issue by sleepymary** [Gogo1951/GogoLoot#59]
Hi I've contacted Softres.it with this issue but they directed me here, and said this is probably a GogoLoot issue.

Since the Classic Era server merge/clusters, the Softres.it + Gogoloot addon do not work well together. From my observation, players would need to have their character names plus server names inside Softres.it for it to work-- FX: Ily-Earthshaker. However this does not seem possible in Softres.it because of the dash.

Because the player's server names are not in the Softres.it sheet, the add-on doesn't recognize them. The only people that the add-on recognizes are the ones that are on the same server as the master looter.

Example:
Ily is on Earthshaker and is the ML.
Valhk is on Earthshaker and reserved items.
Tessa is on Ashbringer and reserved items. 

Valhk's items will be recognised by the add-on, however Tessa's won't be.

Is there any way to fix this so we can use the Softres.it data with GoGoloot?

**Comment by Slivo-fr** [comment]
I experienced this issue too, a fix would be greatly appreciated, even if it does handle the unlikely case of namesake

**Comment by Gogo1951** [comment]
SR will need to add the names to the data they export to us. It'll have to be exported as Joe-Server, not just Joe... that's the only way we'll be able to fix this.

**Comment by Slivo-fr** [comment]
I may be wrong and I cannot test now, but softres does not allow to type the server as part of the playername iirc

**Comment by Gogo1951** [comment]
Not able to reproduce this issue.
