### ISSUE TITLE
Multiple addons repeating message

### ISSUE THREAD

**Issue by Strixen** [Gogo1951/GogoLoot#60]
The 
`GogoLoot : You have multiple addons running that are attempting to interact with the loot window. This will cause problems. If you don't disable your other loot addons you will experience issues with GogoLoot.` message is getting annoying. Can you add a checkbox to acknowledge this so i don't get a message on every zone change. In my case i use RCLC together with gogoloot. However ive set up their thresholds to play nice. 

Love the addon tho. Great work!

**Comment by Gogo1951** [comment]
@Strixen will be fixed in next build.
