### ISSUE TITLE
Avoiding Accidental Looting of World Boss Loot

### ISSUE THREAD

**Issue by davidgroves** [Gogo1951/GogoLoot#63]
Can you find a way to make it harder to avoid accidentally looting untradable world boss loot.

An idea might just be to default all the world boss loot to the default ignore list, since I don't think the API gives any way to determine if loot is tradable or not before you assign it.

**Comment by Gogo1951** [comment]
Hey @davidgroves ,

It should only auto loot if you're in an approved raid instance. Did you have a problem with this, or are you just worried about this?

**Comment by davidgroves** [comment]
There were complains by people that would never know how to raise a git issue that it happened to them, and that gogoloot was blamed. 

I can't be 100% sure it was, but I'm fairly sure it wasn't ninjalooting being blamed on it, as the loot assignment would have made no sense.

**Comment by Gogo1951** [comment]
Probably some bug with the code... it's supposed to only loot when you are in an instance... but looking at the list, it does loot in Kara, and Kara isn't on our old list... sorry mate. This shit gets old to trouble shoot, probably best to tell everyone not to use this addon.

<img width="266" alt="Screen Shot 2021-07-19 at 3 48 43 PM" src="https://user-images.githubusercontent.com/55365231/126225432-23ee2c8a-fb34-409b-b6e5-601c77462a43.png">

**Comment by Gogo1951** [comment]
Hey @davidgroves ,

Will be fixed in upcoming release!

**Comment by Gogo1951** [comment]
Needs to not loot world bosses, go back to only trying to loot BoP when in a specific raid instance. There's also a Tradable flag on items now, no? Maybe we could use that as a sanity check. Classic... ZG, AQ20, AQ40, MC, BWL, Naxx... TBC... Kara, Mag, Gruul's, etc. Never run the autoloot BoPs on outdoor world bosses as those items can not be traded.

**Comment by Gogo1951** [comment]
Looks good!
