### ISSUE TITLE
Set Detault Settings

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#8]
On Install Speedy Loot, Speedy Confirm, and Auto Roll on Boes (Greed) should be set.

**Comment by AeroScripts** [comment]
Are you sure about auto roll? I'm fine with that, but it seems like something that some people would be upset about. lot of people dont look through config ui at all so they might have no idea what addon is auto greeding

**Comment by Gogo1951** [comment]
Yes, let's turn it on by default.

**Comment by Gogo1951** [comment]
Let's turn on Auto Loot too.

**Comment by AeroScripts** [comment]
Should be good with next commit
