### ISSUE TITLE
Empty Persistent Loot Window Issue

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#91]
At times there's an empty persistent loot window, unknown cause. 

Seems to happen more frequently when using the Mouse-wheel-loot method that a lot of farmers / boosters have adopted. Or maybe I just loot more items and have seen it more that way.

Happens in and out of combat. Most commonly seen when on FFA, but also saw it on Master Loot with Threshold Blue in Kara.

**Comment by nicodemus** [comment]
Seen the same thing, I believe it is related to looting while in combat.

**Comment by Kiaos** [comment]
happens mostly in elv ui
